##############################
# Config for LSTM models
##############################

dataset:
  time_list: [9, 12, 15, 18]  # hours; list or 'all'. If 'all', use all hours. The current list = [9, 12, 15, 18]
  train_start: "2016-01-01"  # the start date of the train data; date or 'first'
  train_end: "2021-12-31"  # the end date of the train data; date
  valid_start: "2022-01-01"  # the start date of the validation data; date
  valid_end: "2022-12-31"  # the end date of the validation data; date
  test_start: "2023-01-01"  # the start date of the test data; date
  test_end: "2023-09-30"  # the end date of the test data; date or 'last'
  seq_len_src: 28  # = (num of timestamps in 1 day) * (days); int
  seq_len_tgt: 4  # = (num of timestamps in 1 day) * (days); int
  lag_len: 4  # the nun of lag length in train dataset; int
  batch_size: 64  # the num of batch size; int

model:
  hidden_size: 256  # for LSTM layers
  num_layers: 4  # for LSTM layers
  dropout: 0.2  # for LSTM layers

training:
  n_epochs: 100  # int
  learning_rate: 0.00001  # initial learning rate; float
  milestones: [ 15, 120, 600 ]  # for scheduler; list
  gamma: 0.1  # for scheduler; float
  num_features_pred: 10  # the num of features to be used for prediction. Currently, 10 locations

